### ISSUE TITLE
Invocation directory

### ISSUE THREAD

**Issue by johnhidey** [DonJayamanne/bowerVSCode#1]
Great job @DonJayamanne on this extension and thanks for putting it out there.

I have a project, or group of projects loaded, each in their own folder (Solution create on VS 2015 with multiple projects).  When issuing the command, would be nice to set cwd to the currently open file's directory of folder selected within VSCode.  This would allow for installing of bower packages for several projects within VS code.  

``` Javascript
    var cwd = vscode.workspace.rootPath;
    process.chdir(cwd);
```

Rather than doing the above for each command, possible use the current file's directory or selected folder directory from VS as the `cwd`.  You might even want to check if no `bower.json` then fall back to `vscode.workspace.rootPath` before the invoking of the command.

**Comment by DonJayamanne** [comment]
Great suggestion, thanks. Fixed in latest version.

**Comment by auguster** [comment]
Hello,
It doesn't seem to work with the workspace environnement, it seems that only the first folder of the workspace is used and not the current edited files (and walking up).
Best regards,
